# -*- coding: utf-8 -*-
"""260410.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZP1vOzy6swGnztEdhcyEGcRuh58Kv9NL
"""

i = 0
while i < 5:
  i += 1
  if i == 3:
    continue
  print (i)

a=[1,2,3]
b=["apple","banana"]
c=[1,"hi",3.14,[10,20]]

a

b

c

a.append(4)

a

len(a)

sum(a)

fruits = ["apple", "banana", "orange", "grape", "strawberry"]

fruits.extend(["pineapple", "mango", "peach", "watermelon", "cherry", "kiwi"])

len(fruits)

list(fruits)

for a in fruits:
  print(a)

upper_fruits = []
for fruit in fruits:
  upper_fruits.append(fruit.upper())
print(upper_fruits)

for i,fruit in enumerate(fruits):
  print(f"{i+1}. {fruit}")

kings = [
    "태조", "정종", "태종", "세종", "문종", "단종",
    "세조", "예종", "성종", "연산군", "중종", "인종",
    "명종", "선조", "광해군", "인조", "효종", "현종",
    "숙종", "경종", "영조", "정조", "순조", "헌종",
    "철종", "고종", "순종"]

for i, king in enumerate(kings):
  print(f"{i+1}대. {king}")

n = int(input("몇 대 왕을 찾을까요? : "))

if 1 <= n <= len(kings):
    print(f"{n}대 왕은 {kings[n-1]}입니다.")
else:
    print("1~27 사이로 입력하세요.")

print("세종" in kings)

name = input("왕 이름을 입력하세요: ")

if name in kings:
    idx = kings.index(name)
    print(f"{idx+1}대 왕입니다.")
else:
    print(f"'{name}'은(는) 목록에 없습니다.")

for king in reversed(kings):
  print(king)

