# -*- coding: utf-8 -*-
"""260403.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Edh_XSO5bkRQjU384y4mPHwaVkA3gd5m
"""

import random
answer=random.randint(1,100)

user=int(input("추측값을 입력하시오"))

count=0

while user!=answer:
  if user < answer:
    print("더 큰 수를 입력하시오")
    count+=1
  else:
    print("더 작은 수를 입력하시오")
    count+=1
  user=int(input("추측값을 입력하시오"))
print("총 시도 횟수: ", count)

num = int(input("숫자를 입력하세요: "))

for i in range(1, num + 1):
    if num % i == 0:
        print(i)