# -*- coding: utf-8 -*-
"""260417.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvBnfGxj0tQO1gli_lMes6P7Ot6yWHVD
"""

countries_capitals = {
    "South Korea": "Seoul",
    "Japan": "Tokyo",
    "China": "Beijing",
    "United States": "Washington, D.C.",
    "Canada": "Ottawa",
    "Mexico": "Mexico City",
    "Brazil": "Brasília",
    "Argentina": "Buenos Aires",
    "Chile": "Santiago",
    "United Kingdom": "London",
    "France": "Paris",
    "Germany": "Berlin",
    "Italy": "Rome",
    "Spain": "Madrid",
    "Portugal": "Lisbon",
    "Russia": "Moscow",
    "India": "New Delhi",
    "Thailand": "Bangkok",
    "Vietnam": "Hanoi",
    "Australia": "Canberra"
}

for key, value in countries_capitals.items():
    print(f"{key}의 수도는 {value}입니다.")

cafe_menu = {
    "아메리카노": 4500,
    "카페라떼": 5200,
    "바닐라라떼": 5800,
    "카푸치노": 5200,
    "카라멜마키아토": 5900,
    "콜드브루": 5500,
    "카페모카": 6000,
    "자몽에이드": 5800,
    "레몬에이드": 5800,
    "말차라떼": 6200
}

for key, value in cafe_menu.items():
    print(f"{key}의 가격은 {value}원입니다.")

total_price = sum(cafe_menu.values())
print(f"메뉴 총가격은 {total_price}원입니다.")

total = 0
orders = []

while True:
    order = input("주문할 메뉴를 입력하세요(종료: 끝): ").strip()
    if order == "끝":
        break

    if order in cafe_menu:
        price = cafe_menu[order]
        total += price
        orders.append(order)
        print(f"{order} 추가: {price}원 / 현재 합계: {total}원")
    else:
        print("메뉴에 없습니다. 메뉴명을 정확히 입력해주세요.")

print("주문 내역:", orders)
print(f"총 결제 금액: {total}원")