# -*- coding: utf-8 -*-
"""260508.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZhCsTBB4BYywtRC4j2f916SxiH6ukjR
"""

import pandas as pd
df = pd.DataFrame({
 'name': ['A', 'B', 'C'],
 'score': [90, 80, 70]
})
print(df)

df.to_csv('score.csv')

iris_df = pd.read_csv('Iris.csv')

iris_df

iris_df.shape

iris_df.dtypes

iris_df.head()

