# -*- coding: utf-8 -*-
"""260529.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPyQq3_eJGfE0Bet39nF8Eu1Rr3xBEVv
"""

import pandas as pd
df = pd.read_csv('Iris.csv')


print("데이터 미리보기")
print(df.head())

num_rows = df.shape[0]


num_cols = df.shape[1]

print("총 붓꽃 데이터 개수:", num_rows)
print("총 정보(열) 개수:", num_cols)

print("열 이름 목록")
print(df.columns)

print("기본 정보")
print(df.info())

print("\n각 열의 null 값 개수")
print(df.isnull().sum())


numeric_columns = df.select_dtypes(include='number')

print("\n숫자형 열 개수:", numeric_columns.shape[1])

print("\n숫자형 열 이름")
print(numeric_columns.columns)

count = df[df['PetalLengthCm'] > 2.0].shape[0]
print(count)

result = df[df['SepalWidthCm'] > 3.5]
print(result)

avg_petal = df[df['Species'] == 'Iris-versicolor']['PetalLengthCm'].mean()

print(avg_petal)

max_width = df[df['Species'] == 'Iris-virginica']['SepalWidthCm'].max()

print(max_width)

result = df.groupby('Species')[['SepalLengthCm', 'PetalWidthCm']].mean()

print(result)
# 꽃받침 길이 평균이 가장 긴 종류
longest_sepal = result['SepalLengthCm'].idxmax()

# 꽃잎 너비 평균이 가장 넓은 종류
widest_petal = result['PetalWidthCm'].idxmax()

print("꽃받침이 가장 긴 종류:", longest_sepal)
print("꽃잎이 가장 넓은 종류:", widest_petal)

df['SepalArea'] = df['SepalLengthCm'] * df['SepalWidthCm']
df['PetalArea'] = df['PetalLengthCm'] * df['PetalWidthCm']


avg_sepal_area = df.groupby('Species')['SepalArea'].mean()
avg_petal_area = df.groupby('Species')['PetalArea'].mean()

print("종별 평균 꽃받침 면적:")
print(avg_sepal_area)

print("\n종별 평균 꽃잎 면적:")
print(avg_petal_area)

largest_sepal_area_species = avg_sepal_area.idxmax()

largest_petal_area_species = avg_petal_area.idxmax()

print(f"\n꽃받침 면적이 가장 큰 종류: {largest_sepal_area_species}")
print(f"꽃잎 면적이 가장 큰 종류: {largest_petal_area_species}")

filtered_df = df[(df['SepalWidthCm'] >= 3.0) & (df['PetalWidthCm'] >= 1.5)]

print("필터링된 데이터 미리보기:")
print(filtered_df.head())


species_distribution = filtered_df['Species'].value_counts()

print("\n필터링된 데이터의 종별 개수:")
print(species_distribution)


most_common_species = species_distribution.idxmax()
print(f"\n필터링된 데이터에서 주로 나타나는 종류: {most_common_species}")

import matplotlib.pyplot as plt
plt.rc('font', family="NanumBarunGothic")
petal_mean = df.groupby('Species')['PetalLengthCm'].mean()
plt.bar(petal_mean.index, petal_mean.values)
plt.title('종별 평균 꽃잎 길이 평균')
plt.xlabel('종')
plt.ylabel('평균 꽃잎 길이 (cm)')

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x='PetalLengthCm', y='PetalWidthCm', hue='Species', data=df, s=100, alpha=0.8)
plt.title('꽃잎 길이와 너비의 산점도 (종별 구분)', fontsize=15)
plt.xlabel('꽃잎 길이 (cm)', fontsize=12)
plt.ylabel('꽃잎 너비 (cm)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='종')
plt.show()