# -*- coding: utf-8 -*-
"""260522.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X95FZ5WqhCXGSuTi5ZE0QlNLwV1rZ7pB
"""

# [코드 11-1] 데이터프레임 생성 (딕셔너리 방식)
import pandas as pd

data = {
    'name': ['김철수', '이영희', '박민수', '최지원'],
    'test':    [85, 92, 78, 88],
    'assign1': [90, 85, 80, 95],
    'assign2': [88, 90, 75, 92]
}
df = pd.DataFrame(data)
display(df)  # 또는 print(df)

df

# [코드 11-6, 11-7] 열 추출
df['name']                # 한 개 열 → Series 반환
df[['name', 'test']]      # 두 개 이상 열 → DataFrame 반환

# [코드 11-9] 행 순회
for idx, row in df.iterrows():
    print(idx, row['name'], row['test'])

# [코드 11-10] 열 간 연산
df['sum'] = df['test'] + df['assign1'] + df['assign2']

# [코드 11-11] 조건에 맞는 행 추출
df[df['sum'] >= 80]

df['name']

# [코드 11-13] 열 이름 변경
df = df.rename(columns={'test': 'exam'})

# [코드 11-14] 'sum' 열 기준 내림차순 정렬
sort_df = df.sort_values(by='sum', ascending=False)

# [코드 11-15] 조건에 따라 'grade' 열 생성 (다중 조건)
import numpy as np
df['grade'] = np.where(df['sum'] >= 90, 'A',
              np.where(df['sum'] >= 80, 'B', 'C'))

# [코드 11-16] 합격/불합격 분류
df['result'] = np.where(df['sum'] >= 80, 'pass', 'fail')

# [코드 11-17] 빈도수 확인
df['result'].value_counts()
# pass    3
# fail    1

# [코드 11-19] 열 삭제
df = df.drop(columns=['result'])

sort_df = df.sort_values(by='sum')
sort_df

df['result'] = np.where(df['sum'] >= 260, 'pass', 'fail')

df['result']

df['result'].value_counts()

df.to_csv('exam_out.csv')

df = pd.read_csv('학급당학생수.csv', encoding='EUC-KR')